[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/kontakt.html"
  to = "/kontakt"
  status = 301

[[redirects]]
  from = "/galeria.html"
  to = "/referencie"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
